import { defineConfig } from 'astro/config';

import sitemap from '@astrojs/sitemap';

import playformCompress from '@playform/compress';

export default defineConfig({
  prefetch: false,

  build: {
      // inlineStylesheets: 'never',
  },
  site: 'https://exploremathematics.org',
  integrations: [
    sitemap(), 
    (await import("@playform/compress")).default({
			CSS: false,
			HTML: 
      {
				"html-minifier-terser": {
          caseSensitive: true,
          collapseInlineTagWhitespace: false,
          collapseWhitespace: true,
          continueOnParseError: true,
          decodeEntities: true,
          html5: true,
          // ignoreCustomComments: [],
          // ignoreCustomFragments: never[],
          includeAutoGeneratedTags: false,
          keepClosingSlash: false,
          // This default config file from 
          // https://github.com/PlayForm/Compress/blob/0105b811e2cca694c7a6e4f9dc5824b4325ac73e/Source/Variable/HTML/html-minifier-terser.ts 
          // Keep minifyCSS to false!!!!
          // Keep minifyCSS to false!!!!
          // Keep minifyCSS to false!!!!
          minifyCSS: false,
          minifyJS: true,
          minifyURLs: false,
          noNewlinesBeforeTagClose: true,
          preventAttributesEscaping: false,
          processConditionalComments: false,
          // processScripts: string[],
          // quoteCharacter: string,
          removeAttributeQuotes: false,
          removeComments: true,
          removeScriptTypeAttributes: true,
          removeStyleLinkTypeAttributes: true,
          removeTagWhitespace: false,
          sortAttributes: true,
          sortClassName: true,
          trimCustomFragments: true,
          useShortDoctype: false,
				},
			},
			Image: false,
			JavaScript: false,
			SVG: false,
		}),
  ],
});
